<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>cn.autowork</groupId>
    <artifactId>logoMark</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <name>logoMark</name>

    <properties>
        <maven.compiler.source>18</maven.compiler.source>
        <maven.compiler.target>18</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!-- PDFBox 3.x 模块化 -->
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>3.0.6</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>logo-mark-1.0-mini</finalName>
        <plugins>
            <!-- 编译插件 -->
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>18</release>
                </configuration>
            </plugin>

            <!-- 可执行 JAR -->
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>cn.autowok.logomarker.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.akathist.maven.plugins.launch4j</groupId>
                <artifactId>launch4j-maven-plugin</artifactId>
                <version>1.8.0</version>
                <configuration>
                    <outfile>logoMark.exe</outfile>       <!-- 输出 exe 名称 -->
                    <jar>${project.build.directory}/logo-mark-1.0-mini.jar</jar>  <!-- 主 jar -->
                    <dontWrapJar>false</dontWrapJar>
                    <headerType>gui</headerType>
                    <jreMinVersion>18</jreMinVersion>       <!-- 最低 JRE 版本 -->
                    <bundledJrePath>minijre</bundledJrePath> <!-- 内置裁剪后的 JRE -->
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>launch4j</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
